# /srv/webapps/star-trek-tracker/docker-compose.prod.yml
version: "3.9"
services:
  star-trek-tracker:
    build:
      context: https://github.com/NS-Coding/Star-Trek-Tracker.git#main
      dockerfile: star-trek/Dockerfile
